### PR TITLE
Summary updated and Latin Hypercube Sample for generating Population

### PR DESCRIPTION
**Pull request by yclavinas**
Summary changes:

1. There was a bug in the assert of Y -> object$Y is the correction
2. Implementation of a fair comparison

Latin Hypercube Sample (LHS):

1. By setting in the list named "increments" the value : lhs = TRUE" (increments$lhs = TRUE) it is now possible to generate a new population based on the LHS

### CODE REVIEW

**Comment by yclavinas** [comment]
Missing test

**Comment by fcampelo** [comment]
Thanks for the contribution! Will take a look soon (probably over the weekend).

**Comment by yclavinas** [comment]
In case with work nees review, please let me know!

**Comment by fcampelo** [comment]
Just for reference, please take a look at the _Writing extensions for MOEADr_ vignette.

**Pull request closed without merging**
