### PR TITLE
bug found in variation_polymut

### PR DESCRIPTION
**Pull request by yclavinas**
I understand that the. bug on MOEA/D-DE was in the variation_polymut.R function, where a sum was applied instead of a multiplication.

### CODE REVIEW

**Comment by caranha** [comment]
Hello Yuri, 

Thanks for the submission, can you explain why you think that delta_q should be multplied to X instead of added?

In the original code from emoa, delta_q is also added to X, so can you explain in more detail why it is wrong here?

Also, if you could add a test file (in the test directory) that reproduced/tested for the bug, that would be fantastic.

**Comment by fcampelo** [comment]
> It seems that it is still import to define upper and lower limits values for the polynomial operator even if using scalarization methods.

Not necessarily. **emoa**'s implementation is more general, in the sense that arbitrary variable limits are used along the algorithm. In **MOEADr**'s implementation all variables are internally scaled to the [0,1] interval, and only return to their original ranges at two points:

- when evaluating the objective functions
- at the end of the process, before returning

This allowed me to consider the variable limits for all internal operators as 

- x_{min} = 0
- x_{max} = 1

and, consequently, x_{max} - x_{min} = 1. This greatly simplified the expressions of both the polynomial mutation and SBX recombination (as well as other parts of the algorithm), and obviates the need to explicitly pass these limits to the operators.

**Comment by yclavinas** [comment]
I understand what you are saying. Although, after using the code from the comment above, the error we have been discussing was corrected. 
From that, I would say that it might have to do or with:
1. This approach of scalarizing is not enough.
2. There is a bug related with how it is done. 
3. Something else.

**Comment by fcampelo** [comment]
My bet is on option 2. If my memory doesn't fail me, there are two kinds of "scaling" performed in polynomial mutation / SBX: one uses the bounds of each variable, another uses the max/min of the values *observed* in the population at a given iteration. I may have mixed these two things up when simplifying the formulation of these two operators. 

My suggestion is to work on the original operator definition (e.g., using **emoa**'s implementation as a baseline and writing the mathematical operation that it actually implements) and rework the simplification. I'd do it myself, but I'll only have time (possibly) in November.

**Pull request closed without merging**
